linters:
  enable-all: true
  disable:
    - wsl # Disabled as considered unimportant

# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.15.x # use the fixed version to not introduce new linters unexpectedly