linters:
  enable-all: true
  disable:
#    - dupl # Disabled until neighbourhoods fixed.
#    - interfacer # Disabled as temporarily unimportant
#    - funlen # Disabled as temporarily unimportant
#    - gochecknoglobals # Activated to avoid global variables
#    - gocognit # Disabled as some methods are naturally complex
#    - goconst # Disabled as temporarily unimportant
#    - gocritic # Activated to make code cleaner
#    - gocyclo # Disabled as temporarily unimportant
#    - godox # Disabled as temporarily unimportant
#    - gofmt # Disabled as temporarily unimportant
#    - goimports # Disabled as temporarily unimportant
#    - golint # Disabled as temporarily unimportant
#    - gomnd # Disabled because it is annoying
#    - maligned # Disabled as temporarily unimportant
#    - misspell # Disabled as temporarily unimportant
#    - lll # Disabled to allow long lines of code
#    - scopelint # Activated to avoid scope issues
#    - stylecheck # Disabled as temporarily unimportant
#    - whitespace # Disabled as temporarily unimportant
#    - wsl # Disabled as temporarily unimportant

# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.15.x # use the fixed version to not introduce new linters unexpectedly