# CircleCI 2.0 runs `workflows` of different `jobs`.
# Each `job` (aka as "build") runs terminal/shell (Bash) `command`s.
#
# Reference: https://circleci.com/docs/2.0/configuration-reference/

workflows:
  build-and-test:
    jobs:
    - build-and-test:
        context: org-global
    - lint:
        context: org-global

version: 2.1
jobs:
  build-and-test:
    working_directory: &working_directory /go/src/github.com/Graphmasters/safedown  # only necessary for Golang build (default: `${HOME:?}/project`)
    docker:
      - image: golang:1.14
    steps:
      - checkout
      - run: go version  # To see which Go patch-version is used
      - run:
          name: Unit tests
          command: go test --race  ./...

  lint:
    working_directory: *working_directory
    docker:
      - image: golangci/golangci-lint:latest
    steps:
      - checkout
      - run:
          name: Lint checks (errcheck, etc.)
          command: golangci-lint run